Update typescript interface function definion and bump version to 2.0.0
OAK-Foundation/oak.js pull request #23
Opened 2023-08-05 02:43 UTC by v9n

Follow Step 2 and 3

```
npm install
cd packages/api-augment
npm run clean:defs
npm run generate
```

then run:

```
npm run clean
npm run build
```

Note: I changed the port 8855 in the download-metadata script to my local 2.0.0 rpc node port 9946

2023-08-05 02:55 UTC, chrisli30 requested changes
Hmm I don’t think the events in augment-api-events.ts is updated correctly. Either there’s no logic to pick up the deleted event names, or the local node is still returning them through rpc.

@v9n maybe try to completely delete this file before running the npm scripts?

2023-08-05 02:55 UTC, chrisli30 commented on package.json
> +  "version": "2.0.0-rc.4",
This version needs to be reset to "2.0.0-rc.1", meaning release candidate 1 for 2.0.0

2023-08-05 02:55 UTC, chrisli30 commented on packages/api-augment/src/interfaces/augment-api-events.ts
>        Notify: AugmentedEvent<ApiType, [message: Bytes], { message: Bytes }>;
Isn’t this Notify in automationTime deleted?

2023-08-05 02:55 UTC, chrisli30 commented on packages/api-augment/src/interfaces/augment-api-events.ts
> +      SuccesfullyAutoCompoundedDelegatorStake: AugmentedEvent<ApiType, [taskId: Bytes, amount: u128], { taskId: Bytes, amount: u128 }>;
This should be deleted.

2023-08-05 02:58 UTC, chrisli30 commented
@imstar15, the types package’s code is behind. How do we update the `types` package?
![CleanShot 2023-08-04 at 19 57 39](https://github.com/OAK-Foundation/oak.js/assets/2616844/1c001cbc-bf0d-428f-8dba-7a92b36b1a0d)

2023-08-05 03:10 UTC, imstar15 commented
> @imstar15, the types package’s code is behind. How do we update the `types` package? ![CleanShot 2023-08-04 at 19 57 39](https://user-images.githubusercontent.com/2616844/258559194-1c001cbc-bf0d-428f-8dba-7a92b36b1a0d.png)

This line of configuration also needs to be manually updated to 2.0.0-rc.1.
packages/api-augment/package.json also needs to be manually updated to 2.0.0-rc.1.

2023-08-05 04:39 UTC, chrisli30 commented on package-lock.json
> +      "version": "2.0.0-rc.4",
Discrepancy, `2.0.0-rc.1` but not `2.0.0-rc.4`. The same applies to the line 3.

2023-08-06 19:34 UTC, chrisli30 approved these changes
The changes are published on npm as v2.0.0-rc.1 as tested in xcm-demo code. Good to merge.

@v9n A couple of things to keep in mind of.
1. The commit message `regen` is too simple. Please ALWAYS make sure the message explains the reason a code commit. For example, in the case you can use `Regenerate the api-augment files with the correct oak-blockchain version v2.0.0`
2. The previous version of this PR was incorrect. I assumed that the regenerate scripts ran against an old blockchain code version.

2023-08-07 03:11 UTC, chrisli30 approved these changes

2023-08-09 02:42 UTC, merged